name: 'Build AUR Package'
description: 'Test build an AUR package in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
  build-repo-db:
    description: 'build repo db for host custom single-package repo'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
    - ${{ inputs.build-repo-db }}
