name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - id: check_update
      uses: highFreqSurfer/build-aur-action@master
      with:
        repo-name: conservation_mode
